@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Apr 26 01:44:05 -0400 2020
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto b6f451993918458fb27aa5680d0765db --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot RAM_TB_behav xil_defaultlib.RAM_TB -log elaborate.log"
call xelab  -wto b6f451993918458fb27aa5680d0765db --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot RAM_TB_behav xil_defaultlib.RAM_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
